/*
* generated by Xtext
*/
package it.rcpvision.emf.components.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import it.rcpvision.emf.components.dsl.services.EmfComponentsDslGrammarAccess;

public class EmfComponentsDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EmfComponentsDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected it.rcpvision.emf.components.dsl.parser.antlr.internal.InternalEmfComponentsDslParser createParser(XtextTokenStream stream) {
		return new it.rcpvision.emf.components.dsl.parser.antlr.internal.InternalEmfComponentsDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EmfComponentsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EmfComponentsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
