/*
 * generated by Xtext
 */
package it.rcpvision.emf.components.examples.fowlerdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatemachineRuntimeModule extends it.rcpvision.emf.components.examples.fowlerdsl.AbstractStatemachineRuntimeModule {

}
