/*
* generated by Xtext
*/
package it.rcpvision.emf.components.examples.fowlerdsl.ui.contentassist;

import it.rcpvision.emf.components.examples.fowlerdsl.ui.contentassist.AbstractStatemachineProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StatemachineProposalProvider extends AbstractStatemachineProposalProvider {

}
