/*
* generated by Xtext
*/
package it.rcpvision.emf.components.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EmfComponentsDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
