/*
* generated by Xtext
*/
package it.rcpvision.emf.components.dsl.ui.contentassist;

import it.rcpvision.emf.components.dsl.ui.contentassist.AbstractEmfComponentsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EmfComponentsDslProposalProvider extends AbstractEmfComponentsDslProposalProvider {

}
