/*
 * generated by Xtext
 */
package it.rcpvision.emf.components.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import it.rcpvision.emf.components.dsl.ui.internal.EmfComponentsDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EmfComponentsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EmfComponentsDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EmfComponentsDslActivator.getInstance().getInjector(EmfComponentsDslActivator.IT_RCPVISION_EMF_COMPONENTS_DSL_EMFCOMPONENTSDSL);
	}
	
}
