/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package my.validation;

import java.util.Date;

import my.OrderRow;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link my.Order}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrderValidator {
	boolean validate();

	boolean validateDate(Date value);
	boolean validateOrderNumber(int value);
	boolean validateListOrderRow(EList<OrderRow> value);
}
