/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package my.validation;

import my.Item;

/**
 * A sample validator interface for {@link my.OrderRow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrderRowValidator {
	boolean validate();

	boolean validateItem(Item value);
	boolean validateNumber(int value);
}
