/*
* generated by Xtext
*/
package it.rcpvision.emf.components.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EmfComponentsDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return it.rcpvision.emf.components.dsl.ui.internal.EmfComponentsDslActivator.getInstance().getInjector("it.rcpvision.emf.components.dsl.EmfComponentsDsl");
	}
	
}
