/*
 * generated by Xtext
 */
package it.rcpvision.emf.components.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EmfComponentsDslRuntimeModule extends it.rcpvision.emf.components.dsl.AbstractEmfComponentsDslRuntimeModule {

}
