/*
 * generated by Xtext
 */
package it.rcpvision.emf.components.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EmfComponentsDslUiModule extends it.rcpvision.emf.components.dsl.ui.AbstractEmfComponentsDslUiModule {
	public EmfComponentsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
